---
abstract: 'Adds thresholding to hierarchical clustering of Algorithm::Cluster'
author:
  - 'Chad A. Davis <chad.a.davis@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-Cluster-Thresh
requires:
  Algorithm::Cluster: 0
  perl: 5.008
resources:
  bugtracker: http://github.com/chadadavis/Algorithm-Cluster-Thresh/issues
  homepage: http://github.com/chadadavis/Algorithm-Cluster-Thresh
  repository: http://github.com/chadadavis/Algorithm-Cluster-Thresh
version: 0.05
